config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resource :session, only: %i[new create destroy]
  resources :users, only: %i[new create edit update]
  resources :questions do
    resources :answers, only: %i[create edit update destroy]
  end
  
  #get '/questions', to: 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers, dependent: :destroy
  belongs_to :subject
  validates :text, presence: true
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :questions, dependent: :destroy
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :old_password
  has_secure_password validations: false

  validate :password_presence
  
  
  validate :correct_old_password, on: :update, if: -> { password.present? }

  validates :password, confirmation: true, allow_blank: true
  validate :password_complexity

  
  validates :phone, presence: true, uniqueness: true
  
  private
  
  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,70}$/
    errors.add :password, 'complexity requirement not met. Length should be 8-70 characters and include:
                          1 uppercase, 1 lowercase, 1 digit and 1 special character'
  end
  
  def password_presence
  errors.add(:password, :blank) unless password_digest.present?
  end
  
  def correct_old_password
  return if BCrypt::Password.new(password_digest_was).is_password?(old_password)
  errors.add :old_password, 'is incorrect'
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_question, only: %i[create destroy edit update]
  before_action :set_answer, only: %i[destroy edit update]
  
  def create
    @answer = @question.answers.new answer_params
    if @answer.save
    flash[:success] = "Answer for this question create"
    redirect_to question_path(@question)
    else
      flash[:success] = "Answer don't create"
      render 'questions/show'
    end
  end
  
  def edit
        
  end
  
  def update
    if @answer.update(answer_params)
    flash[:success] = "Answer for this question was updated"
    redirect_to question_path(@question)
    else
      flash[:success] = "Answer wasn't updated"
      render 'edit'
    end
  end
  
  def destroy
    @answer.destroy
    redirect_to question_path(@question)
  end
  
  private
  
  def answer_params
    params.require(:answer).permit(:body, :right, :image_path)
  end
  
  def set_question
    @question = Question.find params[:question_id]
  end
  
  def set_answer
    @answer = @question.answers.find params[:id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  include ErrorHandling
  include Authentication
  
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern
    
    included do
      private
  
      def current_user
        if session[:user_id].present?
          @current_user ||= User.find(session[:user_id]) 
        elsif false
          @current_user = User.find(cookies.encrypted[:user_id])
        end
        
      end
      
      def user_signed_in?
        current_user.present?
      end
      
      def admisible_authentification?
        return unless user_signed_in?
        flash[:warning] = 'You are in sistem!'
        redirect_to root_path
      end
      
      def admisible_logout?
        return if user_signed_in?
        flash[:warning] = 'You cant LogOut, you are not in system'
        redirect_to session_new
      end
      
      def sign_in(user)
        session[:user_id] = user.id
        current_user
        flash[:success] = 'You enter in system'
      end
      
      def sign_out
        session.delete :user_id
        flash[:success] = 'See you later!'
      end
      
      helper_method :current_user, :user_signed_in?
    end
    
end

app/controllers/concerns/error_handling.rb
module ErrorHandling
extend ActiveSupport::Concern
  
  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound

    private

    def notfound(exception)
      logger.warn exception
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @name = params[:name]
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question!, only: %i[show edit update destroy]
  
  def index
    if params.has_key?(:subject_id)
      @pagy, @questions = pagy Question.where(subject_id: params[:subject_id]).order(created_at: :desc)
    else
      @pagy, @questions = pagy Question.order(created_at: :desc)
    end
    
  end
  
  def show
    @answer = @question.answers.build
    @answers = @question.answers.order created_at: :asc
  end
  
  def new
    @question = Question.new
  end
  
  
  def create
    @question = Question.new question_params
    if @question.save
    flash[:success] = 'Question created'
    redirect_to questions_path
    else
    render :new
    end
  end
  
  def edit
  end
  
  def update
    if @question.update(question_params)
    redirect_to questions_path
    else
      render :edit
    end
  end
  
  def destroy
    if @question.destroy
      flash[:success] = 'Question was deleted'
      redirect_to questions_path
    else
      render plain: 'Mistake of delete'
    end
  end
  
  private
  
  def set_question!
    @question = Question.find(params[:id])
  end
  
  def question_params
    params.require(:question).permit(:text, :subject_id)
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :admisible_authentification?, only: %i[new create]
  before_action :admisible_logout?, only: :destroy
  def new
  end
  
  def create
    user = User.find_by(phone: params[:phone])
    if user&.authenticate(params[:password])
      sign_in(user)
      remember(user) if params[:remember_me] == '1'
      redirect_to root_path
    else
      flash[:warning] = 'You get a mistake!'
      redirect_to new_session_path
    end
      
  end
  
  def destroy
  sign_out
  redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :admisible_authentification?, only: %i[new create]
  before_action :admisible_logout?, only: %i[edit update]
  before_action :set_user, only: %i[edit update]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      sign_in(@user)
      redirect_to root_path
    else
    render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update user_params
    flash[:success] = "You change user's parametrs"
    render :edit
    else
    render :edit
    end
  end
  
  private
  
  def set_user
    @user = User.find params[:id]
  end
  
  def user_params
    params.require(:user).permit(:first_name, :second_name, :famaly_name, 
                                  :email, :phone, :password, :password_confirmation, :old_password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
#Подключение навигации для Pagy
  include Pagy::Frontend
# helper для вывода в заголовок динамичного названия стараницы/местонахождения
# Для запуска helpera нужно добавить на соотвтствующей странице provide с аргументом page_title
  
  def full_title(page_title = '')
    page_title.present? ? "TWS | #{page_title}" : "TWS"
  end

  def show_navbar(current_page = '')
    render partial: 'shared/navbar', locals: {current_page: current_page}
  end
  
  def nav_to(title, url, options = {})
    title == options[:current_page] ? appoint_colour = "text-white" : appoint_colour = "text-white-50"
    
    options[:class] += ' ' + appoint_colour
    link_to title, url, options
    
  end
  
  # helper для формирования коллекции тем
  def subject_list
    Subject.order(:body).map { |subject| [subject.body, subject.id] }
  end
  
end

app/views/answers/_answer.html.erb
<div class="col-6">
  <div class="p-3 border bg-light <%=answer.right == true ? 'border-success'  : 'border-danger' %> ">
    <%=answer.body%>
      <div>
        <%=link_to "Delete", question_answer_path(question, answer),
        class: 'btn btn-danger btn-sm', data: {method: :delete}%>
        <%=link_to "Correct answer", edit_question_answer_path(question, answer), class: 'btn 
        btn-secondary btn-sm'%>
    </div>
  </div>
</div>

app/views/answers/_form.html.erb
      <div class="container">
        <%= render 'shared/errors', object: @answer %>
        <%=form_with model: [@question, @answer] do |f|%>
          <div class="mb-3 row">
            <div class="col-2"> <%= f.label :body, class: 'col-form-label' %> </div>
            <div class="col-10"> <%= f.text_area :body, class: 'form-control' %> </div>
          </div>
          
          <div class="mb-3 row">
            <div class="col-2"><%= f.label :right, class: 'col-form-label' %> </div>
            <div class="col-2"><%= f.check_box :right, class: 'form-check-input'%> </div>
          </div>
          
          <div class="mb-3 row">
            <div class="col-2"> <%= f.label :image_path%> </div>
            <div class="col-10"> <%= f.text_area :image_path, class: 'form-control'%> </div>
          </div>
            <div> <%= f.submit 'Create answer', class: 'btn btn-success'%> </div>
        <%end%>
        </div>

app/views/answers/edit.html.erb
<h1> Edit Question </h1>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title><%=full_title(yield(:page_title))%></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield :navbar %>
    
    <main class="container mt-3">
      <% flash.each do |k, v|%>
        <%= tag.div v, class: "alert alert-#{k}" %>
      <%end%>
      
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<% show_navbar('Home') %>
<h1>Example Page for User </h1>
<%=current_user.first_name if user_signed_in?%>
<%= Time.now.year%> 

app/views/questions/_form.html.erb
<%= render 'shared/errors', object: @question %>
<%= form_with model: @question do |f|%>
  <div class="mb-3 row">
    <%= f.text_area :text, size: '70x5',
    placeholder: 'input new question', class: 'form-control-lg mb-3'%>
    <div class="mb-3 row">
      <%= f.select :subject_id, subject_list, {}, class: 'form-select form-select-lg' %> 
    </div>
  </div>
  <div class="mb-3 row">
    <%= f.submit 'Create question', class: 'btn btn-success'%>
  </div>
<%end%> 

app/views/questions/edit.html.erb
<% provide :page_title, 'Questions' %>
<% show_navbar('Questions') %>
<h1> Edit question </h1>
<%= render 'form' %>

app/views/questions/index.html.erb
<% provide :page_title, 'Questions' %>
<% show_navbar('Questions') %>
<h1> All Questions </h1>
<div class='container'>


  <%== pagy_bootstrap_nav @pagy %>
  <%# форма выбора по subject %>

  
    <div> 
      <%=form_with url: questions_path, method: :get do |f|%>
  <div class='row'>
      <div class='col-4'>
      <%= f.select :subject_id, subject_list, {},
                                class: 'form-select form-select-lg mb-3'%>
      </div>
      <div class='col-4'>
      <%=f.submit 'Chose subject', class: 'btn btn-primary btn-lg' %>
      <%= link_to 'Create question', new_question_path, class: 'btn btn-success btn-lg' %>
      </div>
  </div>
      <%end%>
  
  </div>
  
  <% @questions.reverse.each_with_index do |question, num| %>
    <article class="card mp-3 m-2">
      <div class="card-body">
        <section class="card-text">
          <%= @questions.count - num%>.
          <%= question.text%>  
          </p>  
          <time datetime="<%= question.created_at.strftime('%Y-%m-%d %H:%M:%S') %> "> 
            <%= question.created_at%>
          </time>
        </section>
        
          <div class="m-2">
          <%= link_to 'Show question', question_path(question), class: 'btn btn-info' %>
          <%= link_to 'Edit question', edit_question_path(question), class: 'btn btn-secondary'%>
          <%= link_to 'Destroy question', question_path(question), class: 'btn btn-danger',
          data: {method: :delete, confirm: 'Are you sure?'} %>
          </div>
      </div>
      </article>
  <% end %>
  
  <%== pagy_bootstrap_nav @pagy %>

</div>

app/views/questions/new.html.erb
<% provide :page_title, 'Questions' %>
<% show_navbar('Questions') %>
<h1> Add new Question </h1>
<%= render 'form' %>

app/views/questions/show.html.erb
    <% provide :page_title, 'Questions' %>
    <% show_navbar('Questions') %>
    <h2> Question </h2>
    <div class="container">
        <p class="lead my-3"> <%= @question.text%> </p> 
        <time datetime="<%= @question.created_at.strftime('%Y-%m-%d %H:%M:%S') %> "> 
          <%= @question.created_at%>
        </time>
    </div>
      <br> 
      <%# контейнер для ответов %>
      <% unless @answers.nil?%>
          <div class="container">
          <div class="row g-2">
            <%= render partial: 'answers/answer',
              collection: @answers, as: :answer, locals: {question: @question}%>
            </div>
          </div>
      <%end%>
      <%# Конец контейнера ответов %>
      
      <br>
      <%# форма ввода вопроса %>
      <% if @question.answers.count < 4%>
        <%=render 'answers/form' %>
      <%end%>
      <%#конец формы %>
      
    </div>
    
    

app/views/shared/_errors.html.erb
<% if object.errors.full_messages.any? %>
  <ul class="alert alert-danger col-sm-10" >
    <% object.errors.full_messages.each do |error|%>
      <li> <%= error %> </li>
    <%end%>
  </ul>
<%end%>

app/views/shared/_navbar.html.erb
<%= provide :navbar do%>
<header class="p-3 bg-dark text-white">
      <div class="container">
        <nav class="d-flex flex-wrap align-item-center justify-content-center justyfy-content-lg-start">
          <ul class="nav col-lg-auto me-lg-auto mb-2 justify-content-center mb-mb-0" >
            <li>
              <%=nav_to "Home", root_path, class: 'nav-link px-2', current_page: current_page%>
            </li>
            
            <li>
            <%=nav_to "Questions", questions_path, class: 'nav-link px-2', current_page: current_page%>
            </li>
          </ul>
          <ul class="nav col-12 col-lg-auto mb-2 mb-mb-0 ">
            <%if user_signed_in? %>
            <li class="dropdown">
              <%= nav_to current_user.phone, '#', class: 'nav-link px-2 dropdown-toggle', 
                data: {"bs-toggle": 'dropdown'}, current_page: current_page %>
                <ul class="dropdown-menu">
                  <li>
                    <%= link_to "Edit user", edit_user_path(current_user), class: 'dropdown-item'%>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  <li> 
                      <%= link_to 'Log Out', session_path, class: 'dropdown-item',
                      data:{method: :delete} %> 
                  </li>
                  
                  
                </ul>
                
            </li>
            <%else%>
            <li>
              <%=nav_to "Sign Up", new_user_path, class: 'nav-link px-2 ', current_page: current_page %>
            </li>
            
            <li>
              <%=nav_to "Log In", new_session_path, class: 'nav-link px-2 ', current_page: current_page %>
            </li>
            <%end%>
          </ul>
        </nav>
      </div>
    </header>
  <%end%>

app/views/users/_form.html.erb
<%= render 'shared/errors', object: @user %>
<%=form_with model: @user do |f|%>
    <div class='row'>
        <div class='col-3'>
            <p class='form-label'>reference parameters</p>
            <%=f.email_field :email, placeholder: 'Input @mail', class: 'mb-3 form-control' %>
            <%=f.text_field :first_name, placeholder: 'Input first name', class: 'mb-3 form-control' %>
            <%=f.text_field :second_name, placeholder: 'input second name', class: 'mb-3 form-control' %>
            <%=f.text_field :famaly_name, placeholder: 'input famaly name', class: 'mb-3 form-control' %>
        </div>
        <div class='col-3'>
            <p class='form-label'>*mandatory parameters</p>
            <%=f.text_field :phone, placeholder: 'Input password', class: 'mb-3 form-control' %>
            <%=f.password_field :password, placeholder: 'Input password', class: 'mb-3 form-control' %>
            <%=f.password_field :password_confirmation, placeholder: 'Confirm password', class: 'mb-3 form-control' %>
            
        <div>
            <%=f.submit (@user.new_record? ? 'Register' : 'Edit'), class: 'btn btn-success' %>
        </div>
        </div>
        <div class='col-3'>
        <%unless @user.new_record?%>
            <p class='form-label'>*mandatory for chenge password</p>
            <%=f.password_field :old_password, placeholder: 'Old password', class: 'mb-3 form-control' %>
            <%end%>
        </div>
    </div>
<%end%>

app/views/users/edit.html.erb
<% provide :page_title, current_user.phone %>
<% show_navbar(current_user.phone) %>
<h1 class="mb-4"> Edit profile </h1>
<%=render 'form'%>

app/views/users/new.html.erb
<% provide :page_title, 'Regitstration' %>
<% show_navbar('Sign Up') %>
<h1 class='mb-4'> Create new user </h1>
<%= render 'form' %>